debug: false
uuid: b5791c19-e29a-4517-952a-e7622db6d5db
token_id: ybUT96GLFZsITHT4
token: equjy0Ps5owhggrxvrrweEbPiKR72SS4NOcI0R0flYpWGlFUJBdACXfcuP2aQZ3J
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/5.9.67.73/fullchain.pem
    key: /etc/letsencrypt/live/5.9.67.73/privkey.pem
  upload_limit: 256
system:
  data: /var/lib/pelican/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://gaming-pelican-panel-ykl7xt-ec52c7-5-9-67-73.traefik.me'