services:
  pelican-panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    networks:
      - pelican
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDG_DATA_HOME: /pelican-data
      TZ: $TIMEZONE
      APP_TIMEZONE: $TIMEZONE
      APP_ENV: production
      APP_URL: $APP_URL
      ADMIN_EMAIL: $ADMIN_EMAIL
      TRUSTED_PROXIES: $TRUSTED_PROXIES
  
  wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: always
    networks:
      - pelican
    tty: true
    depends_on:
      - pelican-panel
    environment:
      TRUSTED_PROXIES: "*"
      TZ: $TIMEZONE
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pelican/:/etc/pelican/"
      - "/var/lib/pelican/:/var/lib/pelican/"
      - "/var/log/pelican/:/var/log/pelican/"
      - "/tmp/pelican/:/tmp/pelican/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "./wings/config.yml:/etc/pelican/config.yml"

volumes:
  pelican-data:
  pelican-logs:

networks:
  pelican:
    name: pelican
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: pelican