services:
  pelican-panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    networks:
      - pelican
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDG_DATA_HOME: /pelican-data
      TZ: $TIMEZONE
      APP_TIMEZONE: $TIMEZONE
      APP_ENV: production
      APP_URL: $APP_URL
      ADMIN_EMAIL: $ADMIN_EMAIL
      TRUSTED_PROXIES: $TRUSTED_PROXIES
  
volumes:
  pelican-data:
  pelican-logs:

networks:
  pelican:
    name: pelican
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: pelican