services:
  pelican-panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
      - ../files/Caddyfile:/etc/caddy/Caddyfile
    environment:
      XDG_DATA_HOME: /pelican-data
      TZ: $TIMEZONE
      APP_TIMEZONE: $TIMEZONE
      APP_ENV: production
      APP_URL: $APP_URL
      ADMIN_EMAIL: $ADMIN_EMAIL
      TRUSTED_PROXIES: $TRUSTED_PROXIES

volumes:
  pelican-data:
  pelican-logs:
